#!/bin/sh

SLACK_API_TOKEN=""
AZURE_LOG_ANALYTICS_WORKSPACE_ID=""
AZURE_CLIENT_AUTHENTICATION_KEY=""

export SLACK_API_TOKEN=$SLACK_API_TOKEN
export AZURE_LOG_ANALYTICS_WORKSPACE_ID=$AZURE_LOG_ANALYTICS_WORKSPACE_ID
export AZURE_CLIENT_AUTHENTICATION_KEY=$AZURE_CLIENT_AUTHENTICATION_KEY
